In [1]:
import numpy as np
arr=np.array([100,200,300,400])
arr

array([100, 200, 300, 400])

In [2]:
print("Array:", arr)
print("Dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)

Array: [100 200 300 400]
Dimensions: 1
Shape: (4,)
Size: 4

In [3]:
print("Total:", np.sum(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Mean:", np.mean(arr))

Total: 1000
Maximum: 400
Minimum: 100
Mean: 250.0

In [4]:
new_increase=arr*1.10
print(new_increase)

[110. 220. 330. 440.]

In [7]:
data=arr[arr>200]
mark_data=arr>200
print(mark_data)
print(data)

[False False  True  True]
[300 400]

In [1]:
import numpy as np
import pandas as pd

df=pd.read_csv("waste_management.csv")
print(df)

  Bin_ID     Zone  Daily_Waste_KG  Recycled_Waste_KG  Bin_Fill_Percent  \
0   B201    North             120                 45                75
1   B202    South             180                 60                90
2   B203     East              95                 50                55
3   B204     West             220                 70                98
4   B205  Central             150                 80                80
5   B206    North             140                 65                70
6   B207    South              85                 40                45
7   B208     East             200                 55                95
8   B209     West             110                 60                60
9   B210  Central             170                 90                85

   Collection_Delay_Minutes
0                        10
1                        25
2                         0
3                        35
4                        15
5                         5
6                         0
7                        30
8                         8
9                        20

In [2]:
print("Dimensions:", df.ndim)
print("Shape:", df.shape)
print("Size:", df.size)

print('Info:',df.info())
print('Describe:',df.describe())
print('Is Null:',df.isnull())
print('Is Null Count:',df.isnull().sum())

Dimensions: 2
Shape: (10, 6)
Size: 60
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Bin_ID                    10 non-null     str
 1   Zone                      10 non-null     str
 2   Daily_Waste_KG            10 non-null     int64
 3   Recycled_Waste_KG         10 non-null     int64
 4   Bin_Fill_Percent          10 non-null     int64
 5   Collection_Delay_Minutes  10 non-null     int64
dtypes: int64(4), str(2)
memory usage: 612.0 bytes
Info: None
Describe:        Daily_Waste_KG  Recycled_Waste_KG  Bin_Fill_Percent  \
count       10.000000          10.000000         10.000000
mean       147.000000          61.500000         75.300000
std         45.289194          15.465014         17.726628
min         85.000000          40.000000         45.000000
25%        112.500000          51.250000         62.500000
50%        145.000000          60.000000         77.500000
75%        177.500000          68.750000         88.750000
max        220.000000          90.000000         98.000000

       Collection_Delay_Minutes
count                 10.000000
mean                  14.800000
std                   12.354037
min                    0.000000
25%                    5.750000
50%                   12.500000
75%                   23.750000
max                   35.000000
Is Null:    Bin_ID   Zone  Daily_Waste_KG  Recycled_Waste_KG  Bin_Fill_Percent  \
0   False  False           False              False             False
1   False  False           False              False             False
2   False  False           False              False             False
3   False  False           False              False             False
4   False  False           False              False             False
5   False  False           False              False             False
6   False  False           False              False             False
7   False  False           False              False             False
8   False  False           False              False             False
9   False  False           False              False             False

   Collection_Delay_Minutes
0                     False
1                     False
2                     False
3                     False
4                     False
5                     False
6                     False
7                     False
8                     False
9                     False
Is Null Count: Bin_ID                      0
Zone                        0
Daily_Waste_KG              0
Recycled_Waste_KG           0
Bin_Fill_Percent            0
Collection_Delay_Minutes    0
dtype: int64

In [3]:
print("Total waste collected:", df["Daily_Waste_KG"].sum())
print("Maximum waste:", df["Daily_Waste_KG"].max())
print("Minimum waste:", df["Daily_Waste_KG"].min())
print("Average waste:", df["Daily_Waste_KG"].mean())

Total waste collected: 1470
Maximum waste: 220
Minimum waste: 85
Average waste: 147.0

In [4]:
df["Daily_Waste_KG"].to_numpy()

array([120, 180,  95, 220, 150, 140,  85, 200, 110, 170])

In [5]:
print(np.sum(df["Daily_Waste_KG"].to_numpy(), axis=0))

1470

In [6]:
df.head()

,Bin_ID,Zone,Daily_Waste_KG,Recycled_Waste_KG,Bin_Fill_Percent,Collection_Delay_Minutes
0,B201,North,120,45,75,10
1,B202,South,180,60,90,25
2,B203,East,95,50,55,0
3,B204,West,220,70,98,35
4,B205,Central,150,80,80,15

In [7]:
df.tail(4)

,Bin_ID,Zone,Daily_Waste_KG,Recycled_Waste_KG,Bin_Fill_Percent,Collection_Delay_Minutes
6,B207,South,85,40,45,0
7,B208,East,200,55,95,30
8,B209,West,110,60,60,8
9,B210,Central,170,90,85,20

In [8]:
print(df.columns.tolist())

['Bin_ID', 'Zone', 'Daily_Waste_KG', 'Recycled_Waste_KG', 'Bin_Fill_Percent', 'Collection_Delay_Minutes']

In [9]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Bin_ID                    10 non-null     str
 1   Zone                      10 non-null     str
 2   Daily_Waste_KG            10 non-null     int64
 3   Recycled_Waste_KG         10 non-null     int64
 4   Bin_Fill_Percent          10 non-null     int64
 5   Collection_Delay_Minutes  10 non-null     int64
dtypes: int64(4), str(2)
memory usage: 612.0 bytes
None

In [10]:
df["Increased_Waste"] = df["Daily_Waste_KG"] * 1.10

df[["Bin_ID", "Daily_Waste_KG", "Increased_Waste"]]

  Bin_ID  Daily_Waste_KG  Increased_Waste
0   B201             120            132.0
1   B202             180            198.0
2   B203              95            104.5
3   B204             220            242.0
4   B205             150            165.0
5   B206             140            154.0
6   B207              85             93.5
7   B208             200            220.0
8   B209             110            121.0
9   B210             170            187.0

In [11]:
high_waste = df[df["Daily_Waste_KG"] > 150]
high_waste

,Bin_ID,Zone,Daily_Waste_KG,Recycled_Waste_KG,Bin_Fill_Percent,Collection_Delay_Minutes,Increased_Waste
1,B202,South,180,60,90,25,198.0
3,B204,West,220,70,98,35,242.0
7,B208,East,200,55,95,30,220.0
9,B210,Central,170,90,85,20,187.0

In [12]:
high_fill = df[df["Bin_Fill_Percent"] > 80]
high_fill

,Bin_ID,Zone,Daily_Waste_KG,Recycled_Waste_KG,Bin_Fill_Percent,Collection_Delay_Minutes,Increased_Waste
1,B202,South,180,60,90,25,198.0
3,B204,West,220,70,98,35,242.0
7,B208,East,200,55,95,30,220.0
9,B210,Central,170,90,85,20,187.0

In [13]:
df[(df["Daily_Waste_KG"] > 120) & (df["Recycled_Waste_KG"] < 70)]

,Bin_ID,Zone,Daily_Waste_KG,Recycled_Waste_KG,Bin_Fill_Percent,Collection_Delay_Minutes,Increased_Waste
1,B202,South,180,60,90,25,198.0
5,B206,North,140,65,70,5,154.0
7,B208,East,200,55,95,30,220.0

In [14]:
df["Non_Recycled_Waste_KG"] = (
    df["Daily_Waste_KG"] - df["Recycled_Waste_KG"]
)

df[["Bin_ID", "Daily_Waste_KG",
    "Recycled_Waste_KG", "Non_Recycled_Waste_KG"]]

  Bin_ID  Daily_Waste_KG  Recycled_Waste_KG  Non_Recycled_Waste_KG
0   B201             120                 45                     75
1   B202             180                 60                    120
2   B203              95                 50                     45
3   B204             220                 70                    150
4   B205             150                 80                     70
5   B206             140                 65                     75
6   B207              85                 40                     45
7   B208             200                 55                    145
8   B209             110                 60                     50
9   B210             170                 90                     80

In [15]:
non_recycled = df["Non_Recycled_Waste_KG"]

print("Total non-recycled waste:", non_recycled.sum())
print("Average non-recycled waste:", non_recycled.mean())
print("Minimum non-recycled waste:", non_recycled.min())
print("Maximum non-recycled waste:", non_recycled.max())

Total non-recycled waste: 855
Average non-recycled waste: 85.5
Minimum non-recycled waste: 45
Maximum non-recycled waste: 150